name: 'Build & Push Platforms JS'

on:
  workflow_call:
    inputs:
      subscription-code:
        type: string
        required: true

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build-push:
    name: Build and Push

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ env.GH_PAT }}
          
      - name: Fetch config files
        run: |
          mkdir -p packages/n3o-elements/src

          wget -O app.json https://cdn.n3o.cloud/connect-${{ inputs.subscription-code }}/build/app.json
          wget -O themes.json https://cdn.n3o.cloud/connect-${{ inputs.subscription-code }}/build/themes.json

          jq -n \
            --argfile app app.json \
            --argfile themes themes.json \
            '{app: $app, search: $search, features: $features, themes: $themes}' \
            > packages/n3o-elements/src/configuration.json

      - name: npm install and build
        run: |
          npm install --legacy-peer-deps
          npx turbo build:lib --filter=@n3oltd/n3o-elements
        env:
          NODE_AUTH_TOKEN: ${{ env.GH_PAT }}
          VITE_SUBSCRIPTION_CODE: ${{ inputs.subscription-code }}

      - name: npm publish
        working-directory: packages/n3o-elements
        run: |
          version=$(date +"%Y.%m.%d")-${{ github.run_number }}
          name="@n3oltd/platforms-js-${{ inputs.subscription-code }}"
          jq "del(.devDependencies, .scripts, .dependencies) | .name = \"$name\"" package.json > tmp.json && mv tmp.json package.json
          npm version $version;
          echo "//npm.pkg.github.com/:_authToken=${{ env.GH_PAT }}" >> .npmrc;
          echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc;
          npm publish;
